Repository pexip/pexshell, pull requests merged in 2023-02, with the labels that each got.

#2 Add a lock to the config file
  Cargo.lock
  Cargo.toml
  src/argparse/cache.rs
  src/argparse/login.rs
  src/config.rs
  src/pexshell.rs
Labels: feature

#5 fix windows build
  Cargo.toml
  src/main.rs
Labels: bug

#7 fix config tests after file locking
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/pexshell.rs
Labels: testing, bug
