Repository pexip/pexshell, pull requests merged in 2023-03, with the labels that each got.

#12 security: automatically create dependabot PRs
  .github/dependabot.yml
Labels: ci

#15 add missing license field to lib and test_helpers crates
  about.toml
  lib/Cargo.toml
  test_helpers/Cargo.toml
Labels: housekeeping

#18 initialise config with default log file path
  lib/src/util/logging.rs
  src/config.rs
  src/end_to_end_tests/cache.rs
  src/end_to_end_tests/delete.rs
  src/end_to_end_tests/get.rs
  src/end_to_end_tests/get_all.rs
  src/end_to_end_tests/mod.rs
  src/end_to_end_tests/patch.rs
  src/end_to_end_tests/post.rs
  src/main.rs
  src/pexshell.rs
  src/test_util.rs
Labels: refactoring

#22 Add elvish, nushell and powershell completions
  Cargo.lock
  Cargo.toml
  src/argparse/completions.rs
Labels: feature

#24 prevent pexshell asking for keychain access twice
  src/argparse/login.rs
  src/cli/login.rs
  src/config.rs
Labels: bug

#28 logging: create parent directories of log file if they do not exist
  lib/src/util/logging.rs
Labels: bug

#27 clean up clippy lints
  Cargo.lock
  Cargo.toml
  lib/Cargo.toml
  lib/src/lib.rs
  lib/src/mcu/error.rs
  lib/src/mcu/mod.rs
  lib/src/mcu/schema.rs
  lib/src/util/future.rs
  lib/src/util/stream.rs
  src/argparse/cache.rs
  src/argparse/completions.rs
  src/cli/login.rs
  src/cli/mod.rs
  src/config.rs
  src/main.rs
  src/pexshell.rs
  test_helpers/src/fs/cache.rs
  test_helpers/src/future.rs
  test_helpers/src/lib.rs
Labels: refactoring

#34 docs: update installation from source instruction in README
  README.md
Labels: docs

#38 config: print feedback message when waiting for file lock
  Cargo.lock
  Cargo.toml
  src/argparse/login.rs
  src/cli/login.rs
  src/config.rs
  src/pexshell.rs
Labels: refactoring, feature

#29 Add last_used timestamp to User
  src/argparse/cache.rs
  src/argparse/login.rs
  src/cli/login.rs
  src/config.rs
  src/pexshell.rs
  test_helpers/src/fs/config.rs
Labels: feature

#39 Display "last used" in local timezone
  src/cli/login.rs
Labels: feature

#56 ci: fix cargo-nextest version to 0.9.50
  .github/actions/prepare/action.yml
  .github/workflows/test.yml
Labels: ci
